logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter=DEBUG:
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:delivery_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
server:
  port : 8090